### ISSUE TITLE
Multiple Streams using AioQuic

### ISSUE THREAD

**Issue by devkdas** [LautaroJayat/go_auth_proxy_example#1]
hai ,

It is not an issue.
one small quick query

@LautaroJayat 
Could you please confirm were you able to create multiple streams in a single connection using the AIOQUIC code you have in Github.

Sorry for raising an issue as i am unable to find your email to ask this query.

Looking forward for your reply

Thank you.

**Comment by LautaroJayat** [comment]
Hi,
I haven't used it yet. I forked the repo just to read the implementation but, until now, I didn't have the time.

**Comment by devkdas** [comment]
Hai @LautaroJayat 

Thank you for replying back.

okay,Please let me know if you use this in future and if you able to create multiple streams.

Thank you.
@Karthikdasari0423
